// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentUP.Data;

#nullable disable

namespace TalentUP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714123824_AjudanteNullable")]
    partial class AjudanteNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentUP.Models.Badge.BadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("BadgeEntities");
                });

            modelBuilder.Entity("TalentUP.Models.Colaborador.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pontuacao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("TalentUP.Models.Pontuacao.PontuacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorPontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PontuacaoEntities");
                });

            modelBuilder.Entity("TalentUP.Models.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AjudanteId")
                        .HasColumnType("int");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AjudanteId");

                    b.HasIndex("CriadorId");

                    b.ToTable("taskEntities");
                });

            modelBuilder.Entity("TalentUP.Models.Badge.BadgeEntity", b =>
                {
                    b.HasOne("TalentUP.Models.Colaborador.Colaborador", null)
                        .WithMany("Badges")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentUP.Models.TaskEntity", b =>
                {
                    b.HasOne("TalentUP.Models.Colaborador.Colaborador", "Ajudante")
                        .WithMany("TasksAjudadas")
                        .HasForeignKey("AjudanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentUP.Models.Colaborador.Colaborador", "Criador")
                        .WithMany("TasksCriadas")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ajudante");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("TalentUP.Models.Colaborador.Colaborador", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("TasksAjudadas");

                    b.Navigation("TasksCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
